version: '2'

services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
